apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: 647496772601.dkr.ecr.us-east-1.amazonaws.com/ncryptify/citrus:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
