apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: naveentest
# Example configuration for the webserver
# at https://github.com/monopole/hello

metadata:
  name: arbitrary

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml



