apiVersion: apps/v1
kind: Deployment
metadata:
  name: nitish
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: nitish9282/nginx:v1
        name: guestbook-ui
        ports:
        - containerPort: 80
